export const SUBMIT_PENDING = 'SUBMIT_PENDING';
export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';
export const SUBMIT_FAIL = 'SUBMIT_FAIL';
export const LOGOUT = 'LOGOUT';
export const GETUSERS_PENDING = 'GETUSERS_PENDING';
export const GETUSERS_SUCCESS = 'GETUSERS_SUCCESS';
export const GETUSERS_FAIL = 'GETUSERS_FAIL';
export const LOAD_USER_FROM_TOKEN = 'LOAD_USER_FROM_TOKEN';
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';
export const GET_CURRENT_USER_DETAIL_PENDING = 'GET_CURRENT_USER_DETAIL_PENDING';
export const GET_CURRENT_USER_DETAIL_SUCCESS = 'GET_CURRENT_USER_DETAIL_SUCCESS';
export const GET_CURRENT_USER_DETAIL_FAIL = 'GET_CURRENT_USER_DETAIL_FAIL';
export const EDIT_CURRENT_USER_DETAIL = 'EDIT_CURRENT_USER_DETAIL';
export const EDIT_CURRENT_USER_DETAIL_SUCCESS = 'EDIT_CURRENT_USER_DETAIL_SUCCESS';
export const EDIT_CURRENT_USER_DETAIL_FAIL = 'EDIT_CURRENT_USER_DETAIL_FAIL';
export const SUBMIT_UPDATED_USER_DETAIL_PENDING = 'SUBMIT_UPDATED_USER_DETAIL_PENDING';
export const SUBMIT_UPDATED_USER_DETAIL_SUCCESS = 'SUBMIT_UPDATED_USER_DETAIL_SUCCESS';
export const SUBMIT_UPDATED_USER_DETAIL_FAIL = 'SUBMIT_UPDATED_USER_DETAIL_FAIL';




